apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: pd-serve-tmpl
  annotations:
    scenarios.ai.sap.com/description: "Payment Delay Prediction"
    scenarios.ai.sap.com/name: "payment-delay-prediction"
    executables.ai.sap.com/description: "XGBoost serving endpoint"
    executables.ai.sap.com/name: "pd-serve"
  labels:
    scenarios.ai.sap.com/id: "payment-delay-prediction"
    ai.sap.com/version: "1.0"
spec:
  inputs:
    parameters:
      - name: greetmessage
        type: string
    artifacts:
      - name: paymentmodel
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 0
      labels: |
        ai.sap.com/resourcePlan: infer.s
    spec: |
      predictor:
        imagePullSecrets:
          - name: docker-hub-srini117us
        minReplicas: 1
        maxReplicas: 1
        containers:
          - name: kserve-container
            image: docker.io/srini117us/payment-delay-serve:1.0
            ports:
              - containerPort: 9001
                protocol: TCP
            env:
              - name: STORAGE_URI
                value: "{{inputs.artifacts.paymentmodel}}"