apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: churn-model-serving
  annotations:
    scenarios.ai.sap.com/description: "Serve customer churn prediction model"
    scenarios.ai.sap.com/name: "churn-serving"
    executables.ai.sap.com/description: "Churn prediction REST API"
    executables.ai.sap.com/name: "churn-server"
  labels:
    scenarios.ai.sap.com/id: "churn-serving"
    ai.sap.com/version: "1.0.0"
spec:
  inputs:
    artifacts:
      - name: churnmodel
    parameters:
      - name: minReplicas
        type: string
        default: "1"
      - name: maxReplicas
        type: string
        default: "2"
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    kind: "InferenceService"
    metadata:
      labels: |
        ai.sap.com/resourcePlan: starter
      annotations: |
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: "1"
        autoscaling.knative.dev/targetBurstCapacity: "0"
    spec: |
      predictor:
        minReplicas: {{inputs.parameters.minReplicas}}
        maxReplicas: {{inputs.parameters.maxReplicas}}
        containers:
          - name: kserve-container
            image: docker.io/srini117us/churn-serving:v1
            ports:
              - containerPort: 8080
                protocol: TCP
            env:
              - name: MODEL_PATH
                value: /mnt/models
            volumeMounts:
              - name: model-storage
                mountPath: /mnt/models
        volumes:
          - name: model-storage
            persistentVolumeClaim:
              claimName: "{{inputs.artifacts.churnmodel}}"
