apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: churn-serve-v3
  annotations:
    scenarios.ai.sap.com/description: "Churn model serving"
    scenarios.ai.sap.com/name: "churn-serve-v3"
    executables.ai.sap.com/description: "Churn server"
    executables.ai.sap.com/name: "churn-srv-v3"
  labels:
    scenarios.ai.sap.com/id: "churn-serve-v3"
    ai.sap.com/version: "1.0.0"
spec:
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 0
      labels: |
        ai.sap.com/resourcePlan: starter
    spec: |
      predictor:
        imagePullSecrets:
          - name: default
        minReplicas: 1
        maxReplicas: 1
        containers:
          - name: kserve-container
            image: docker.io/srini117us/churn-serving:v2
            ports:
              - containerPort: 8080
                protocol: TCP
