
---
apiVersion: v1
kind: Config
current-context: f4bac9c0trial-2fv1p8yy
clusters:
- name: f4bac9c0trial-2fv1p8yy
  cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ1akNDQWs2Z0F3SUJBZ0lRU1JHUVBkVGV5SG95M0p5QTcyYTdwVEFOQmdrcWhraUc5dzBCQVFzRkFEQU4KTVFzd0NRWURWUVFERXdKallUQWVGdzB5TmpBek1qWXlNREF5TXpKYUZ3MHpOakF6TWpZeU1EQXpNekphTUEweApDekFKQmdOVkJBTVRBbU5oTUlJQm9qQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FZOEFNSUlCaWdLQ0FZRUEwaERECkhGR0hwYXVCV2JFZW00akMvMWdadlR0bC9rWVRLWTRGYVo1VThMWU05aVpJY2h1UXh4eHllZ3B0UkFsd2xOUk4KR3UvZEVDVFJYVWRlVmd6QnlhSVY5dCtlRVRnc20zbWZBM0xBcnFKZEhhS0hidE1SWnRiVnZnb1pmeWNsakZtbgpYd3p6YmhIZVpvb2RJeGlNQ3J5ajhtdnF0cnpVZnQ4MkRyYm1YZlo0N0djYUZVMXZUVFZXbGV0SEF6d0dXTCtmCmlQTDhNdHJzdDEyWklnR2E5bjY4QmFDa25wSHRvOEs4UitIQUdVbHV1bm02YzBWTXBaY0VnRDBHNm9XSFo3cnYKSHM2eUh5Rmc3aTZjWG5ubWZZcHBNL25LRThyNmkwUG5MOTBCMjNCQ0h2Uyt6cGVva3FlYmRCMmtjbHJlbkdBTApqRThlQ1FjOHJ2WkQzYUhVNWdKS29MWWZGakdFSzJFNGlKZ1JlWEtPdy9iSHJTa0lHSk9SU2VURnhrKy9lQTBVCmR2em03R3hHSmZiR3kvQjZQZXNqSU52YnJJYTY4am1oMkFnZms4YVZMbm9HSjdhVldmdDg3RW5GWFZYcE95WWcKcmk2L3gzU29PSjlXbVpoUTNBTnl2ZXFoWi9GSm5EVExrR2dmL1dGSFRpT1JFUmo5Q0M1aU13UDgzcjlsQWdNQgpBQUdqUWpCQU1BNEdBMVVkRHdFQi93UUVBd0lCcGpBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXCkJCU0duQU5VRHBRZkl4dUJCNFhoZGkwMzc4SlpjREFOQmdrcWhraUc5dzBCQVFzRkFBT0NBWUVBTnZPb3pKOFAKWmllVDVHMHh1WGxVN2pyekhIbHNQNzdSN0tpZWVFblA2NEdCdG9aQjhxYVZvTGhmNjliUE9oUkJiK0tUSmJIZgpzMVExUlE1VzFLVUxCWlNQd1NCS1lqVDNKbnNnTFJGcHl1cGRNUkk5YUR5bS83Y2FxM3JXWGhHeFRCQUlaYkpmCkF4N2ZORGl5ZDcrbC8xSFdlWHNBOExuVmdwQlBXR2ExU21MV0tYQzl2SU1qS212MjlGbjF3UC9zWXNaMUljdGYKeGlOZlQ4RU5zQXVuMWxaZFdnQ2NHYUVOR0pKZ2V4UUg0L05SemxwcUlIc1RkYjFzMXRpeUM2WER4WHRjRm9JMwphNDFMODNTRHlNNW5QNnQrcUxoR2pBUjZWSDN2S0tDeGlQOXhQTTBwUFhLTTI0RnRYUXVTYXJRL0hmazMwMXdCCnlSRjhvSERvNG1UNW1aUDRWUUNzUHJNdzVKMkFOeW5iMG5BNzhHQWZuSVJuZ3IyckVlTFRIVFUrdG1ZdkdmRlUKTFBNaUFCU3ZqMEVnb3F2WmlRN2JWR2JXMktPaVRlMXYvK2pjUHJjbHVqekFtZ0hwNENFSXJ6N2YrNDlXYk5kZwpHalpzZXZmVDhSTHYrSnhBeUFEOWwwVFNIRDZIK1F1R1NCb3JzQmxub2ZPK3ppSFhxR2MrVWcvcAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://api.c-92c0b83.kyma.ondemand.com
contexts:
- name: f4bac9c0trial-2fv1p8yy
  context:
    cluster: f4bac9c0trial-2fv1p8yy
    user: f4bac9c0trial-2fv1p8yy
users:
- name: f4bac9c0trial-2fv1p8yy
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - "--oidc-issuer-url=https://kyma.accounts.ondemand.com"
      - "--oidc-client-id=12b13a26-d993-4d0c-aa08-5f5852bbdff6"
      - "--oidc-extra-scope=email"
      - "--oidc-extra-scope=openid"
      command: kubectl-oidc_login
      installHint: |
        kubelogin plugin is required to proceed with authentication
        # Homebrew (macOS and Linux)
        brew install int128/kubelogin/kubelogin

        # Krew (macOS, Linux, Windows and ARM)
        kubectl krew install oidc-login

        # Chocolatey (Windows)
        choco install kubelogin
